### PR TITLE
Rewrite from the ground up, adds a number of features, addresses issues

### LINKED ISSUE #17: Blobs are not dumped correctly
When I try to dump tables with blobs, the module is going to generate MySQL syntax errors by adding an additional single quote before the value.

Example:
BLOB Value: `613a303a7b7d`
Output in INSERT statement:

```
[...] '1',NULL,'',NULL,NULL,''613a303a7b7d',NULL [...]
                             ^
```

This leads to problems with exporting BLOB-including tables.

### LINKED ISSUE #24: How to use mysqldump in ionic2
Please let me know how to use this npm for ionic2

### LINKED ISSUE #29: Views are not dumped.
I have a view in my database and it resulted in `undefined;` line in the resulting SQL dump which in turn causes applications that use the dump to fail on that line.

Are views not supported? If not, can we have that fixed so that we don't get an `undefined` in the dump output?

### LINKED ISSUE #30: Very high memory footprint
At first thanks for the nice lib :)

I am trying to use your library for a small DB dump using AWS Lambda.

native mysqldump size ~45MB
nodejs mysqldump size ~90MB

Though this is not the problem. What got me irritated was the very high memory footprint. Lambda says it uses 800MB of RAM to build the 90MB dump. Is this supported to be like that?

Have you thought about implementing some streaming API where we could pipe the result directly to some gzip filter?

### LINKED ISSUE #32: RangeError: Invalid string length
Hi,

I'm using this library to backup a single database nightly but all of a sudden the backups have stopped working with the following error.  I'm not sure where to begin debugging this, any pointers would be much appreciated!

```
/bundle/bundle/programs/server/npm/node_modules/mysqldump/index.js:163
                  callback(null,results.createSchemaDump.concat(results.createDataDump).join("\n\n"));
                                                                                        ^
RangeError: Invalid string length
    at Array.join (native)
    at Array.async.auto.getDataDump (/bundle/bundle/programs/server/npm/node_modules/mysqldump/index.js:163:74)
    at listener (/bundle/bundle/programs/server/npm/node_modules/async/lib/async.js:605:42)
    at /bundle/bundle/programs/server/npm/node_modules/async/lib/async.js:544:17
    at _arrayEach (/bundle/bundle/programs/server/npm/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/bundle/bundle/programs/server/npm/node_modules/async/lib/async.js:543:13)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

### PR DESCRIPTION
**Pull request by bradzacher**
- rewrote into typescript
  - split code across a number of files so it's easier to maintain.
  - added build step to generate typescript types: Fixes #24
- changed to a promise-based API
- added tests across entire codebase (100% coverage!)
- improved memory footprint by streaming the data dump.
  - Fixes #30
  - Fixes #32
- Added new features
  - view dumping: Fixes #29
  - blob dumping: Fixes #17
  - added configurability to reduce the size of the dumped SQL by trimming unneeded parts of the definitions.
  - added the ability to run a sql formatter over the dump.
  - added the ability to dump triggers
  - added the ability to split insert statements after X rows
  - added session variables to the dump to help with large, relational databases.

### CODE REVIEW

**Comment by Dafrok** [comment]
seems like https://github.com/Dafrok/mysql-backup/blob/master/index.js

**Comment by bradzacher** [comment]
mysql-backup looks to be more of a more API compatible upgrade.

this is intended to be a ground-up feature-compatible rewrite, with new features enabled by a new code structure.

`mysqldump` is a library used within our infrastructure at assignar, so we needed something that is a bit more robust - hence the test coverage.
Additionally, we needed extra features - such as view dumping.

Rather than publishing this as an extra library and having them compete/have people choose between the two, or keeping it as an entirely internal module - we decided it was a better idea to try and release it as an improved mysqldump.

I have contacted @webcaetano a few times about wanting to take over ownership/management of the package (because it's a core piece of our infrastructure, it would be well maintained by our engineers).

He has not responded to my emails, so instead I'm trying a different avenue.

We currently publish and consume this version of package via our namespace on NPM: https://www.npmjs.com/package/@assignar/mysqldump, but would love it to be widely available outside the namespace.

**Comment by bradzacher** [comment]
Hi there, this PR has been open for a month.

Is there the possibility of merged, or having it looked at?

**Comment by Ashoat** [comment]
@bradzacher, maybe you could publish your fork to npm?

**Comment by bradzacher** [comment]
This fork is published to NPM, and it's available at https://www.npmjs.com/package/@assignar/mysqldump

**Comment by Ashoat** [comment]
Sorry, I somehow completely missed you linking that at the end of your previous comment...

**Comment by bradzacher** [comment]
no problem!
if you find a bug, raise an issue on https://github.com/assignar/mysqldump and I'll look into it.

**Comment by bradzacher** [comment]
Took me a bit to figure out how to get it working properly on travis (never used it before!), but you can see the build and test running and completing successfully, with 100% test coverage.

**Comment by webcaetano** [comment]
@bradzacher sorry for late response. 
Just saw the npmjs email. 
I'll transfer the ownership for you on this.

**Pull request merged**
