### PR TITLE
introduce support for 'fancy' data types

### PR DESCRIPTION
**Pull request by marching-cube**
Hello. 

I would like to extend support for complex data types. To this end, I propose the following changes to the library:

1. Fixing support for binary data types (such as BLOB, BINARY, VARBINARY, BIT).
Binary literals, such as X'ABCD', are escaped, stripped and then escaped again using 'escapeUnquoted' function. This produces invalid literals, f.e.: ''ABCD'. Replacing 'escapeUnquoted' with a direct call to 'mysql.escape' fixed the problem.
Reference: 'Blobs are not dumped correctly #17'

2. Adding support for geometric values (such as POINT, LINESTRING, POLYGON, MULTIPOINT, MULTILINESTRING, MULTIPOLYGON, GEOMETRYCOLLECTION).
- GEOMETRY values are parsed by MySQL library as either plain objects (only the POINT type) or plain arrays (all the other types). 'mysql.escape' does not handle these correctly, instead addition of 'escapeGeometryType()' was necessary. This function recursively creates literals of a form similar to: "ST_GeomFromText('POINT(1 2)')".
- the above solution, however, depends on the knowledge of dynamic types of geometric values. MySQL library obtains these internally, but does not expose to consumers (a variable called wkbType in Parser.js). That's why the 'typeCast' callback was necessary, and within it the 'annotateWkbTypes' function that recursively extracts dynamic types from a raw packet data.

3. Extending unit test coverage ('should dump all the fancy data types correctly').
- SETUP1: create a 'data_types' table containing variables of (almost) all possible data types,
- SETUP2: insert a sample data row (that will be processed during the test phase).
- STEP1: dump contents of the 'data_types' table (tests if dump library executes without issues),
- STEP2: execute dump sql onto 'data_types' (tests for dump sql's syntactic correctness),
- STEP3: select both rows (setup and insert) and compare contents field by field  (tests for dump sql's content correctness)

4. (Refactoring) Extracting the MySQL connection variables (host, user, password) into shared constants. Makes it easier to run tests on MySQL environments with different setups. 

Best regards

### CODE REVIEW

**Comment by marching-cube** [comment]
The tests are most likely failing due to a lack of support for JSON data type (MySQL >=5.7.8 required).
Not sure what MySQL version Travis is running on, but removing JSON related lines, fixed the CREATE TABLE call on MySQL 5.6.29. 

I would gladly remove the offending lines, just not sure how to proceed. Should I create a new pull request?

**Comment by webcaetano** [comment]
@marching-cube Hi, 
i'll review that soon. I'm very busy this week.

**Comment by marching-cube** [comment]
@webcaetano Thank you.

**Comment by webcaetano** [comment]
@marching-cube 40f083c

https://docs.travis-ci.com/user/database-setup/#MySQL-5.6
https://docs.travis-ci.com/user/trusty-ci-environment/#Using-Trusty

Thank you.

**Comment by dashmug** [comment]
@marching-cube Thank you for your work on this.

@webcaetano When will these commits be released?

**Comment by webcaetano** [comment]
@dashmug oh yeah, i forgot to make a minor version.

**Comment by dashmug** [comment]
@webcaetano Thanks.

**Pull request merged**
