### PR TITLE
insert all rows at once *untested*

### PR DESCRIPTION
**Pull request by atomfried**
should be way more efficient.

### CODE REVIEW

**Comment by atomfried** [comment]
Note however that this breaks on certain servers:
http://stackoverflow.com/questions/16491039/maximum-query-length-to-avoid-epipe-error-in-node-js

So it should be optional I guess.

**Comment by webcaetano** [comment]
@atom That's great. 
I'll review that soon. And create tests. 
Thanks

**Comment by abelosorio** [comment]
Any advance on this feature? I think it's not `minor` at all.

Thanks

**Comment by bradzacher** [comment]
superseded by #44

**Pull request closed without merging**
